(cl:defpackage pronto_msgs-msg
  (:use )
  (:export
   "<BIPEDFORCETORQUESENSORS>"
   "BIPEDFORCETORQUESENSORS"
   "<CONTROLLERFOOTCONTACT>"
   "CONTROLLERFOOTCONTACT"
   "<FILTERSTATE>"
   "FILTERSTATE"
   "<GPSDATA>"
   "GPSDATA"
   "<INDEXEDMEASUREMENT>"
   "INDEXEDMEASUREMENT"
   "<LIDARODOMETRYUPDATE>"
   "LIDARODOMETRYUPDATE"
   "<QUADRUPEDFORCETORQUESENSORS>"
   "QUADRUPEDFORCETORQUESENSORS"
   "<QUADRUPEDSTANCE>"
   "QUADRUPEDSTANCE"
   "<VELOCITYWITHSIGMABOUNDS>"
   "VELOCITYWITHSIGMABOUNDS"
   "<VISUALODOMETRYUPDATE>"
   "VISUALODOMETRYUPDATE"
  ))

