// Generated by gencpp from file pronto_msgs/BipedForceTorqueSensors.msg
// DO NOT EDIT!


#ifndef PRONTO_MSGS_MESSAGE_BIPEDFORCETORQUESENSORS_H
#define PRONTO_MSGS_MESSAGE_BIPEDFORCETORQUESENSORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Wrench.h>
#include <geometry_msgs/Wrench.h>
#include <geometry_msgs/Wrench.h>
#include <geometry_msgs/Wrench.h>

namespace pronto_msgs
{
template <class ContainerAllocator>
struct BipedForceTorqueSensors_
{
  typedef BipedForceTorqueSensors_<ContainerAllocator> Type;

  BipedForceTorqueSensors_()
    : header()
    , l_foot()
    , r_foot()
    , l_hand()
    , r_hand()  {
    }
  BipedForceTorqueSensors_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , l_foot(_alloc)
    , r_foot(_alloc)
    , l_hand(_alloc)
    , r_hand(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _l_foot_type;
  _l_foot_type l_foot;

   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _r_foot_type;
  _r_foot_type r_foot;

   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _l_hand_type;
  _l_hand_type l_hand;

   typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _r_hand_type;
  _r_hand_type r_hand;





  typedef boost::shared_ptr< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> const> ConstPtr;

}; // struct BipedForceTorqueSensors_

typedef ::pronto_msgs::BipedForceTorqueSensors_<std::allocator<void> > BipedForceTorqueSensors;

typedef boost::shared_ptr< ::pronto_msgs::BipedForceTorqueSensors > BipedForceTorqueSensorsPtr;
typedef boost::shared_ptr< ::pronto_msgs::BipedForceTorqueSensors const> BipedForceTorqueSensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator1> & lhs, const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.l_foot == rhs.l_foot &&
    lhs.r_foot == rhs.r_foot &&
    lhs.l_hand == rhs.l_hand &&
    lhs.r_hand == rhs.r_hand;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator1> & lhs, const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pronto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "608f43cae98f77f5fb6cfbbbfa4c9253";
  }

  static const char* value(const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x608f43cae98f77f5ULL;
  static const uint64_t static_value2 = 0xfb6cfbbbfa4c9253ULL;
};

template<class ContainerAllocator>
struct DataType< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pronto_msgs/BipedForceTorqueSensors";
  }

  static const char* value(const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Atlas force torque sensors for the wrists and ankles\n"
"Header header\n"
"\n"
"geometry_msgs/Wrench l_foot\n"
"geometry_msgs/Wrench r_foot\n"
"geometry_msgs/Wrench l_hand\n"
"geometry_msgs/Wrench r_hand\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.l_foot);
      stream.next(m.r_foot);
      stream.next(m.l_hand);
      stream.next(m.r_hand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BipedForceTorqueSensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pronto_msgs::BipedForceTorqueSensors_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "l_foot: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.l_foot);
    s << indent << "r_foot: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.r_foot);
    s << indent << "l_hand: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.l_hand);
    s << indent << "r_hand: ";
    s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.r_hand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRONTO_MSGS_MESSAGE_BIPEDFORCETORQUESENSORS_H
