// Generated by gencpp from file pronto_msgs/FilterState.msg
// DO NOT EDIT!


#ifndef PRONTO_MSGS_MESSAGE_FILTERSTATE_H
#define PRONTO_MSGS_MESSAGE_FILTERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace pronto_msgs
{
template <class ContainerAllocator>
struct FilterState_
{
  typedef FilterState_<ContainerAllocator> Type;

  FilterState_()
    : header()
    , quat()
    , state()
    , cov()  {
    }
  FilterState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , quat(_alloc)
    , state(_alloc)
    , cov(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _quat_type;
  _quat_type quat;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _state_type;
  _state_type state;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _cov_type;
  _cov_type cov;





  typedef boost::shared_ptr< ::pronto_msgs::FilterState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pronto_msgs::FilterState_<ContainerAllocator> const> ConstPtr;

}; // struct FilterState_

typedef ::pronto_msgs::FilterState_<std::allocator<void> > FilterState;

typedef boost::shared_ptr< ::pronto_msgs::FilterState > FilterStatePtr;
typedef boost::shared_ptr< ::pronto_msgs::FilterState const> FilterStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pronto_msgs::FilterState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pronto_msgs::FilterState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pronto_msgs::FilterState_<ContainerAllocator1> & lhs, const ::pronto_msgs::FilterState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.quat == rhs.quat &&
    lhs.state == rhs.state &&
    lhs.cov == rhs.cov;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pronto_msgs::FilterState_<ContainerAllocator1> & lhs, const ::pronto_msgs::FilterState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pronto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pronto_msgs::FilterState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pronto_msgs::FilterState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pronto_msgs::FilterState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pronto_msgs::FilterState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pronto_msgs::FilterState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pronto_msgs::FilterState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pronto_msgs::FilterState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be4439d283f2f4408baf08ace05ca824";
  }

  static const char* value(const ::pronto_msgs::FilterState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe4439d283f2f440ULL;
  static const uint64_t static_value2 = 0x8baf08ace05ca824ULL;
};

template<class ContainerAllocator>
struct DataType< ::pronto_msgs::FilterState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pronto_msgs/FilterState";
  }

  static const char* value(const ::pronto_msgs::FilterState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pronto_msgs::FilterState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Quaternion quat\n"
"float64[] state\n"
"float64[] cov\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::pronto_msgs::FilterState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pronto_msgs::FilterState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.quat);
      stream.next(m.state);
      stream.next(m.cov);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FilterState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pronto_msgs::FilterState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pronto_msgs::FilterState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "quat: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quat);
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state[i]);
    }
    s << indent << "cov[]" << std::endl;
    for (size_t i = 0; i < v.cov.size(); ++i)
    {
      s << indent << "  cov[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.cov[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRONTO_MSGS_MESSAGE_FILTERSTATE_H
