// Generated by gencpp from file pronto_msgs/VelocityWithSigmaBounds.msg
// DO NOT EDIT!


#ifndef PRONTO_MSGS_MESSAGE_VELOCITYWITHSIGMABOUNDS_H
#define PRONTO_MSGS_MESSAGE_VELOCITYWITHSIGMABOUNDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace pronto_msgs
{
template <class ContainerAllocator>
struct VelocityWithSigmaBounds_
{
  typedef VelocityWithSigmaBounds_<ContainerAllocator> Type;

  VelocityWithSigmaBounds_()
    : header()
    , velocity_plus_one_sigma()
    , velocity_minus_one_sigma()
    , plus_one_sigma()  {
    }
  VelocityWithSigmaBounds_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity_plus_one_sigma(_alloc)
    , velocity_minus_one_sigma(_alloc)
    , plus_one_sigma(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_plus_one_sigma_type;
  _velocity_plus_one_sigma_type velocity_plus_one_sigma;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_minus_one_sigma_type;
  _velocity_minus_one_sigma_type velocity_minus_one_sigma;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _plus_one_sigma_type;
  _plus_one_sigma_type plus_one_sigma;





  typedef boost::shared_ptr< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityWithSigmaBounds_

typedef ::pronto_msgs::VelocityWithSigmaBounds_<std::allocator<void> > VelocityWithSigmaBounds;

typedef boost::shared_ptr< ::pronto_msgs::VelocityWithSigmaBounds > VelocityWithSigmaBoundsPtr;
typedef boost::shared_ptr< ::pronto_msgs::VelocityWithSigmaBounds const> VelocityWithSigmaBoundsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator1> & lhs, const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity_plus_one_sigma == rhs.velocity_plus_one_sigma &&
    lhs.velocity_minus_one_sigma == rhs.velocity_minus_one_sigma &&
    lhs.plus_one_sigma == rhs.plus_one_sigma;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator1> & lhs, const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pronto_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f91adbed2b2172ae0f78e162a5bc17d";
  }

  static const char* value(const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f91adbed2b2172aULL;
  static const uint64_t static_value2 = 0xe0f78e162a5bc17dULL;
};

template<class ContainerAllocator>
struct DataType< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pronto_msgs/VelocityWithSigmaBounds";
  }

  static const char* value(const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# convenience message encoding the linear velocity\n"
"# one sigma bounds (plus, minus) and the sigma alone\n"
"\n"
"Header header\n"
"geometry_msgs/Vector3 velocity_plus_one_sigma\n"
"geometry_msgs/Vector3 velocity_minus_one_sigma\n"
"geometry_msgs/Vector3 plus_one_sigma\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity_plus_one_sigma);
      stream.next(m.velocity_minus_one_sigma);
      stream.next(m.plus_one_sigma);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityWithSigmaBounds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pronto_msgs::VelocityWithSigmaBounds_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity_plus_one_sigma: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_plus_one_sigma);
    s << indent << "velocity_minus_one_sigma: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_minus_one_sigma);
    s << indent << "plus_one_sigma: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.plus_one_sigma);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRONTO_MSGS_MESSAGE_VELOCITYWITHSIGMABOUNDS_H
