# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pronto_msgs/GPSData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class GPSData(genpy.Message):
  _md5sum = "79674b2d1f8526159c0504accff3f259"
  _type = "pronto_msgs/GPSData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
uint64 utime
int32 gps_lock
float64 longitude
float64 latitude
float64 elev
float64 horizontal_accuracy
float64 vertical_accuracy
uint32 num_satellites
float64 speed
float64 heading
float64[3] xyz_pos
float64 gps_time


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','utime','gps_lock','longitude','latitude','elev','horizontal_accuracy','vertical_accuracy','num_satellites','speed','heading','xyz_pos','gps_time']
  _slot_types = ['std_msgs/Header','uint64','int32','float64','float64','float64','float64','float64','uint32','float64','float64','float64[3]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,utime,gps_lock,longitude,latitude,elev,horizontal_accuracy,vertical_accuracy,num_satellites,speed,heading,xyz_pos,gps_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GPSData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.utime is None:
        self.utime = 0
      if self.gps_lock is None:
        self.gps_lock = 0
      if self.longitude is None:
        self.longitude = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.elev is None:
        self.elev = 0.
      if self.horizontal_accuracy is None:
        self.horizontal_accuracy = 0.
      if self.vertical_accuracy is None:
        self.vertical_accuracy = 0.
      if self.num_satellites is None:
        self.num_satellites = 0
      if self.speed is None:
        self.speed = 0.
      if self.heading is None:
        self.heading = 0.
      if self.xyz_pos is None:
        self.xyz_pos = [0.] * 3
      if self.gps_time is None:
        self.gps_time = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.utime = 0
      self.gps_lock = 0
      self.longitude = 0.
      self.latitude = 0.
      self.elev = 0.
      self.horizontal_accuracy = 0.
      self.vertical_accuracy = 0.
      self.num_satellites = 0
      self.speed = 0.
      self.heading = 0.
      self.xyz_pos = [0.] * 3
      self.gps_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Qi5dI2d().pack(_x.utime, _x.gps_lock, _x.longitude, _x.latitude, _x.elev, _x.horizontal_accuracy, _x.vertical_accuracy, _x.num_satellites, _x.speed, _x.heading))
      buff.write(_get_struct_3d().pack(*self.xyz_pos))
      _x = self.gps_time
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.utime, _x.gps_lock, _x.longitude, _x.latitude, _x.elev, _x.horizontal_accuracy, _x.vertical_accuracy, _x.num_satellites, _x.speed, _x.heading,) = _get_struct_Qi5dI2d().unpack(str[start:end])
      start = end
      end += 24
      self.xyz_pos = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 8
      (self.gps_time,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Qi5dI2d().pack(_x.utime, _x.gps_lock, _x.longitude, _x.latitude, _x.elev, _x.horizontal_accuracy, _x.vertical_accuracy, _x.num_satellites, _x.speed, _x.heading))
      buff.write(self.xyz_pos.tostring())
      _x = self.gps_time
      buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.utime, _x.gps_lock, _x.longitude, _x.latitude, _x.elev, _x.horizontal_accuracy, _x.vertical_accuracy, _x.num_satellites, _x.speed, _x.heading,) = _get_struct_Qi5dI2d().unpack(str[start:end])
      start = end
      end += 24
      self.xyz_pos = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 8
      (self.gps_time,) = _get_struct_d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_Qi5dI2d = None
def _get_struct_Qi5dI2d():
    global _struct_Qi5dI2d
    if _struct_Qi5dI2d is None:
        _struct_Qi5dI2d = struct.Struct("<Qi5dI2d")
    return _struct_Qi5dI2d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
