(cl:in-package fovis_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          NUM_MATCHES-VAL
          NUM_MATCHES
          NUM_INLIERS-VAL
          NUM_INLIERS
          NUM_DETECTED_KEYPOINTS-VAL
          NUM_DETECTED_KEYPOINTS
          NUM_REPROJECTION_FAILURES-VAL
          NUM_REPROJECTION_FAILURES
          NUM_KEYPOINTS-VAL
          NUM_KEYPOINTS
          MEAN_REPROJECTION_ERROR-VAL
          MEAN_REPROJECTION_ERROR
          FAST_THRESHOLD-VAL
          FAST_THRESHOLD
          STATUS-VAL
          STATUS
))